### ISSUE TITLE
有点问题

### ISSUE THREAD

**Issue by yangfan920215** [copyrenzhe/novel#3]
file_get_contents(/data/wwwroot/yangfan.ren/test/public/build/rev-manifest.json): failed to open stream: No such file or directory (View: /data/wwwroot/yangfan.ren/test/resources/views/app.blade.php) (View: /data/wwwroot/yangfan.ren/test/resources/views/app.blade.php)

**Comment by copyrenzhe** [comment]
项目根目录执行 gulp
